spring:
  profiles:
    active:
    - dev
---
server: 
  port: 7001 
spring:
  profiles: dev.eureka.node1
  application: 
    name: fengniaowuspringcloud
eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己。
    fetch-registry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
       defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址。
      #defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/

---
server: 
  port: 9999 
spring:
  profiles: dev.fengniaowu.consumer
  application: 
    name: fengniaowuspringcloud
feign: 
  hystrix: 
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
 
---
server: 
  port: 10000
spring:
  profiles: dev.fengniaowu.hystrixdashboard
  application: 
    name: fengniaowuspringcloud

---
server: 
  port: 9527
spring:
  profiles: dev.fengniaowu.zuulgeteway
  application: 
    name: fengniaowuspringcloud-zuulgeteway

eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
zuul:
  prefix: /fengniaowu #设置统一的前缀
  ignored-services: "*"   #原真实名称忽略  单个具体，多个可以用"*"
  routes: 
    mydept.serviceId: fengniaowuspringcloud #必须是对应的applictionName
    mydept.path: /talos/**    #自定义代理名称访问


info:
  app.name: fengniaowu-microcloud
  company.name: www.fengniaowu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server: 
  port: 8001 
spring:
  profiles: dev.provider.department
  application: 
    name: fengniaowuspringcloud-department
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    filters: stat,wall,log4j
    logSlowSql: true
    driver-class-name: com.mysql.jdbc.Driver                # mysql驱动包
    url: jdbc:mysql://192.168.1.68:3307/cloudDB01              # 数据库名称
    username: root
    password: 323323
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    instance-id: fengniaowuspringcloud-department   #自定义服务名称信息
    prefer-ip-address: true
    
info:
  app.name: fengniaowu-microservicecloud
  company.name: www.fengniaowu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$info.app

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.fengniaowu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
---
server: 
  port: 8002
spring:
  profiles: dev.provider.apartment
  application: 
    name: fengniaowuspringcloud-apartment
  datasource:
    url: jdbc:sqlserver://kc-fengniaowu-dev.database.chinacloudapi.cn:1433;DatabaseName=KC.Fengniaowu.Talos-Dev
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: KC
    password: V245ZGxbEhn3Sakk
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200   

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
    instance-id: fengniaowuspringcloud-aepartment   #自定义服务名称信息
    prefer-ip-address: true

info:
  app.name: fengniaowu-microservicecloud
  company.name: www.fengniaowu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$info.app

    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.fengniaowu.springcloud.entities    # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件